In [1]:
import pandas as pd
import pickle

In [2]:

dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:

dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:

independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dependent=dataset[['classification_yes']]

In [9]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [10]:
independent.shape

(399, 27)

In [11]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.model_selection import GridSearchCV
param_grid= {'penalty':['l1', 'l2', 'elasticnet'],'random_state':[0],
             'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']} 

grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
55 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 436, in _check_solver
    % (all_solvers, solver)
ValueError: Logistic Regression supports only solvers in ['liblinear', 'newton-cg', 'lbfgs', 'sag', 'saga'], got newton-cholesky.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 459, in _check_solver
    solver
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1473, in fit
    % self.l1_ratio
ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [       nan 0.97507379        nan        nan        nan 0.97858525
 0.99288844 0.97156632 0.99288844        nan 0.98577688 0.97862588
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,
C:\Users\MANIKA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l1', 'l2', 'elasticnet'],
                         'random_state': [0],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [16]:
re=grid.cv_results_
y_predict=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
cm

array([[45,  0],
       [ 1, 74]], dtype=int64)

In [17]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_predict)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_predict,average='weighted')
print("The f1 macro value the best parameter{}:".format(grid.best_params_),f1_macro)

The f1 macro value the best parameter{'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs'}: 0.9916844900066377

In [18]:
print(cm)

[[45  0]
 [ 1 74]]

In [19]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_random_state,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002992,0.001669,0.000000,0.000000,l1,0,lbfgs,"{'penalty': 'l1', 'random_state': 0, 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
1,0.009770,0.001936,0.003591,0.000798,l1,0,liblinear,"{'penalty': 'l1', 'random_state': 0, 'solver':...",1.000000,0.982221,0.982221,0.947015,0.963912,0.975074,0.018085,6
2,0.002794,0.001163,0.000000,0.000000,l1,0,newton-cg,"{'penalty': 'l1', 'random_state': 0, 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
3,0.002394,0.001017,0.000000,0.000000,l1,0,newton-cholesky,"{'penalty': 'l1', 'random_state': 0, 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
4,0.001797,0.001172,0.000000,0.000000,l1,0,sag,"{'penalty': 'l1', 'random_state': 0, 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
5,0.036701,0.004945,0.004188,0.002631,l1,0,saga,"{'penalty': 'l1', 'random_state': 0, 'solver':...",1.000000,0.982221,0.982221,0.964572,0.963912,0.978585,0.013392,5
6,0.020349,0.006268,0.002992,0.000638,l2,0,lbfgs,"{'penalty': 'l2', 'random_state': 0, 'solver':...",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
7,0.007974,0.002519,0.002992,0.000630,l2,0,liblinear,"{'penalty': 'l2', 'random_state': 0, 'solver':...",0.964572,0.982221,0.964572,0.964572,0.981894,0.971566,0.008567,7
8,0.025534,0.002861,0.003192,0.000748,l2,0,newton-cg,"{'penalty': 'l2', 'random_state': 0, 'solver':...",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
9,0.002596,0.000491,0.000000,0.000000,l2,0,newton-cholesky,"{'penalty': 'l2', 'random_state': 0, 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
10,0.018350,0.003546,0.002995,0.001543,l2,0,sag,"{'penalty': 'l2', 'random_state': 0, 'solver':...",0.982221,0.982221,0.982221,0.982221,1.000000,0.985777,0.007112,3
11,0.021741,0.006414,0.002793,0.001324,l2,0,saga,"{'penalty': 'l2', 'random_state': 0, 'solver':...",0.982221,0.982221,0.964572,0.982221,0.981894,0.978626,0.007028,4
12,0.001395,0.000487,0.000000,0.000000,elasticnet,0,lbfgs,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
13,0.002194,0.000398,0.000000,0.000000,elasticnet,0,liblinear,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
14,0.002392,0.000796,0.000000,0.000000,elasticnet,0,newton-cg,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
15,0.001994,0.000630,0.000000,0.000000,elasticnet,0,newton-cholesky,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
16,0.001795,0.000399,0.000000,0.000000,elasticnet,0,sag,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
17,0.001595,0.000488,0.000000,0.000000,elasticnet,0,saga,"{'penalty': 'elasticnet', 'random_state': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18

In [4]:
filename="LOGISTIC_final.sav"
pickle.dump(classifier.open(filename,"wb"))
with open('my_dumped_classifier.pkl', 'rb') as fid:

NameError: name 'classifier' is not defined

In [27]:
age_input=int(input("Age:"))
bp_input=int(input("BP:"))
al_input=int(input("AL:"))
su_input=int(input("SU:"))
bgr_input=int(input("BGR:"))
bu_input=int(input("BU:"))
sc_input=int(input("SC:"))
sod_input=int(input("SOD:"))
pot_input=int(input("POT:"))
hrmo_input=int(input("HRMO:"))
pcv_input=int(input("PCV:"))
wc_input=int(input("WC:"))
rc_input=int(input("RC:"))
sg_b_input=int(input("SGB:"))
sg_c_input=int(input("SGC:"))
sg_d_input=int(input("SGD:"))
sg_e_input=int(input("SGE:"))
sg_b_input=int(input("SGB:"))
rbc_normal_input=int(input("RBC_NORMAL:"))
pc_normal_input=int(input("PC_NORMAL:"))
pcc_present_input=int(input("PC_PRESENT:"))
ba_present_input=int(input("BA_PRESENT:"))
htn_yes_input=int(input("HTN_YES:"))
dm_yes_input=int(input("DM_YES:"))
cad_yes_input=int(input("CAD_YES:"))
appet_yes_input=int(input("APPET_YES:"))
pe_yes_input=int(input("PE_YES:"))
ane_yes_input=int(input("ANE_YES:"))

Age:3
BP:80
AL:3
SU:0
BGR:150
BU:58
SC:4
SOD:136
POT:5
HRMO:13
PCV:1
WC:1
RC:1
SGB:0
SGC:1
SGD:0
SGE:1
SGB:0
RBC_NORMAL:1
PC_NORMAL:1
PC_PRESENT:0
BA_PRESENT:1
HTN_YES:1
DM_YES:1
CAD_YES:1
APPET_YES:0
PE_YES:0
ANE_YES:1

In [31]:
future_Prediction=grid.predict([[age_input,bp_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,sg_b_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(future_Prediction))

Future_Prediction=[1]